source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               icons/,\
               rsc/
src.includes = rsc/,\
               icons/,\
               .classpath,\
               .polyglot.META-INF,\
               .project,\
               .settings/,\
               DRAG_DROP_IMPLEMENTATION.md,\
               doc/,\
               plugin.xml,\
               src/
